### ISSUE TITLE
Product Card on Mobile devices rendering the single image.

### ISSUE THREAD

**Issue by vtrixe** [vtrixe/desire-store#1]
When opening the product card on mobile devices the gallery only renders a single image of the product

**Comment by Ishan19agarwal** [comment]
**Modification Suggestions:**
To improve the responsiveness of the product card, consider the following changes:
For the **product card**, update the class as follows:
From:

```html
<div class="mx-auto mt-6 hidden w-full max-w-2xl sm:block lg:max-w-none"> 
To:
<div class="mx-auto mt-6 w-full max-w-2xl">

And in index.tsx, modify the class from:
<div class="mx-auto mt-6 hidden w-full max-w-2xl sm:block lg:max-w-none">
To:
<div class="mx-auto mt-6 w-full max-w-2xl">
